name: ${addon-name}
main: ${main-class}
version: ${project.version}
description: Scatter addon plugin for UHC
author: ghowden/Eluinhost
website: wiki.publicuhc.com
database: false
depend: [UltraHardcore]
commands:
    sct:
        description: Scatter players
        usage: /<command>
        aliases: [uhcsct]
permissions:
    UHC.scatter.command:
        description: Use the scatter command
        default: op